const posts = [
  {
    id: 1,
    title:
    'Software Engineer',
    body: `Bu yigit ozgina harakat, xoxish va ishtiyoq bo'lsa dasturlashni o'zi uni oldiga kelishini isbotlagan va bir necha ming dollar turuvchi dasturlash kursida tekunga o'qish, o'rganish imkonini qo'lga kiritgan Andijonlik yigit hisoblanada.`,
    user: {
      id: 1,
      name: 'Shuhratbek Qobulov',
      username: '@mrshukhratbek',
      email: 'https://shuhratbekqobulov@gmail.com',
      phone: '+998902045988',
      website: '/images/shukhratbek.jpg',
    },
    comments: [
      {
        id: 1,
        name: 'id labore ex et quam laborum',
        email: 'Eliseo@gardner.biz',
        body: 'laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium',
      },
      {
        id: 2,
        name: 'quo vero reiciendis velit similique earum',
        email: 'Jayne_Kuhic@sydney.com',
        body: 'est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et',
      },
      {
        id: 3,
        name: 'odio adipisci rerum aut animi',
        email: 'Nikita@garfield.biz',
        body: 'quia molestiae reprehenderit quasi aspernatur\naut expedita occaecati aliquam eveniet laudantium\nomnis quibusdam delectus saepe quia accusamus maiores nam est\ncum et ducimus et vero voluptates excepturi deleniti ratione',
      },
      {
        id: 4,
        name: 'alias odio sit',
        email: 'Lew@alysha.tv',
        body: 'non et atque\noccaecati deserunt quas accusantium unde odit nobis qui voluptatem\nquia voluptas consequuntur itaque dolor\net qui rerum deleniti ut occaecati',
      },
      {
        id: 5,
        name: 'vero eaque aliquid doloribus et culpa',
        email: 'Hayden@althea.biz',
        body: 'harum non quasi et ratione\ntempore iure ex voluptates in ratione\nharum architecto fugit inventore cupiditate\nvoluptates magni quo et',
      },
    ],
  },
  {
    id: 11,
    title: `Agar javob bermasam yoki xabaringizni o'qimasam yana yozing. Uzr.)`,
    body: 'Bu yigit Dasturlashni self-study ya\'ni ustozsiz ham mukammal o\'rganish mumkinligini isbotlagan Buxorolik TATU talabasi hisoblanadi.',
    user: {
      id: 2,
      name: 'Abdumajid Rashidov',
      username: '@abdumajid_rashidov',
      email: 'https://shuhratbekqobulov@gmail.com',
      phone: '+998916469095',
      website: '/images/abdumajid.jpg',
    },
    comments: [
      {
        id: 51,
        name: 'molestias et odio ut commodi omnis ex',
        email: 'Laurie@lincoln.us',
        body: 'perferendis omnis esse\nvoluptate sit mollitia sed perferendis\nnemo nostrum qui\nvel quis nisi doloribus animi odio id quas',
      },
      {
        id: 52,
        name: 'esse autem dolorum',
        email: 'Abigail.OConnell@june.org',
        body: 'et enim voluptatem totam laudantium\nimpedit nam labore repellendus enim earum aut\nconsectetur mollitia fugit qui repellat expedita sunt\naut fugiat vel illo quos aspernatur ducimus',
      },
      {
        id: 53,
        name: 'maiores alias necessitatibus aut non',
        email: 'Laverne_Price@scotty.info',
        body: 'a at tempore\nmolestiae odit qui dolores molestias dolorem et\nlaboriosam repudiandae placeat quisquam\nautem aperiam consectetur maiores laboriosam nostrum',
      },
      {
        id: 54,
        name: 'culpa eius tempora sit consequatur neque iure deserunt',
        email: 'Kenton_Vandervort@friedrich.com',
        body: 'et ipsa rem ullam cum pariatur similique quia\ncum ipsam est sed aut inventore\nprovident sequi commodi enim inventore assumenda aut aut\ntempora possimus soluta quia consequatur modi illo',
      },
      {
        id: 55,
        name: 'quas pariatur quia a doloribus',
        email: 'Hayden_Olson@marianna.me',
        body: 'perferendis eaque labore laudantium ut molestiae soluta et\nvero odio non corrupti error pariatur consectetur et\nenim nam quia voluptatum non\nmollitia culpa facere voluptas suscipit veniam',
      },
    ],
  },
  {
    id: 21,
    title: 'I have got a dream that is worth more than my sleep.',
    body: 'Repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nNihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt',
    user: {
      id: 3,
      name: 'Dostonbek Qurolboyev',
      username: '@dostonbek_qurolboyev',
      email: 'dastonbekofficial@gmail.com',
      phone: '+998881207788',
      website: '/images/me.jpg',
    },
    comments: [
      {
        id: 101,
        name: 'perspiciatis magnam ut eum autem similique explicabo expedita',
        email: 'Lura@rod.tv',
        body: 'ut aut maxime officia sed aliquam et magni autem\nveniam repudiandae nostrum odio enim eum optio aut\nomnis illo quasi quibusdam inventore explicabo\nreprehenderit dolor saepe possimus molestiae',
      },
      {
        id: 102,
        name: 'officia ullam ut neque earum ipsa et fuga',
        email: 'Lottie.Zieme@ruben.us',
        body: 'aut dolorem quos ut non\naliquam unde iure minima quod ullam qui\nfugiat molestiae tempora voluptate vel labore\nsaepe animi et vitae numquam ipsa',
      },
      {
        id: 103,
        name: 'ipsum a ut',
        email: 'Winona_Price@jevon.me',
        body: 'totam eum fugiat repellendus\nquae beatae explicabo excepturi iusto et\nrepellat alias iure voluptates consequatur sequi minus\nsed maxime unde',
      },
      {
        id: 104,
        name: 'a assumenda totam',
        email: 'Gabriel@oceane.biz',
        body: 'qui aperiam labore animi magnam odit est\nut autem eaque ea magni quas voluptatem\ndoloribus vel voluptatem nostrum ut debitis enim quaerat\nut esse eveniet aut',
      },
      {
        id: 105,
        name: 'voluptatem repellat est',
        email: 'Adolph.Ondricka@mozell.co.uk',
        body: 'ut rerum illum error at inventore ab nobis molestiae\nipsa architecto temporibus non aliquam aspernatur omnis quidem aliquid\nconsequatur non et expedita cumque voluptates ipsam quia\nblanditiis libero itaque sed iusto at',
      },
    ],
  },
  {
    id: 31,
    title: 'Постав цел🎯, Создай план🧾, И подними жопу🍑!',
    body: 'Debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae',
    user: {
      id: 4,
      name: 'Abdurahim Nurmatov',
      username: '@rewico',
      email: 'Julianne.OConner@kory.org',
      phone: '+998330222238',
      website: '/images/abdurakhim.jpg',
    },
    comments: [
      {
        id: 151,
        name: 'ut quas facilis laborum voluptatum consequatur odio voluptate et',
        email: 'Cary@taurean.biz',
        body: 'quos eos sint voluptatibus similique iusto perferendis omnis voluptas\nearum nulla cumque\ndolorem consequatur officiis quis consequatur aspernatur nihil ullam et\nenim enim unde nihil labore non ducimus',
      },
      {
        id: 152,
        name: 'quod doloremque omnis',
        email: 'Tillman_Koelpin@luisa.com',
        body: 'itaque veritatis explicabo\nquis voluptatem mollitia soluta id non\ndoloribus nobis fuga provident\nnesciunt saepe molestiae praesentium laboriosam',
      },
      {
        id: 153,
        name: 'dolorum et dolorem optio in provident',
        email: 'Aleen@tania.biz',
        body: 'et cumque error pariatur\nquo doloribus corrupti voluptates ad voluptatem consequatur voluptas dolores\npariatur at quas iste repellat et sed quasi\nea maiores rerum aut earum',
      },
      {
        id: 154,
        name: 'odit illo optio ea modi in',
        email: 'Durward@cindy.com',
        body: 'quod magni consectetur\nquod doloremque velit autem ipsam nisi praesentium ut\nlaboriosam quod deleniti\npariatur aliquam sint excepturi a consectetur quas eos',
      },
      {
        id: 155,
        name: 'adipisci laboriosam repudiandae omnis veritatis in facere similique rem',
        email: 'Lester@chauncey.ca',
        body: 'animi asperiores modi et tenetur vel magni\nid iusto aliquid ad\nnihil dolorem dolorum aut veritatis voluptates\nomnis cupiditate incidunt',
      },
    ],
  },
  {
    id: 41,
    title: 'Kecha aytganimdek ertaga hammasi yaxshi boladi.☝️☝️☝️☝️',
    body: 'molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe',
    user: {
      id: 5,
      name: 'Gulmurod',
      username: '@murod_95',
      email: 'Lucio_Hettinger@annie.ca',
      phone: '+998977340112',
      website: '/images/gulmurod.jpg',
    },
    comments: [
      {
        id: 201,
        name: 'et adipisci aliquam a aperiam ut soluta',
        email: 'Cleve@royal.us',
        body: 'est officiis placeat\nid et iusto ut fugit numquam\neos aut voluptas ad quia tempore qui quibusdam doloremque\nrecusandae tempora qui',
      },
      {
        id: 202,
        name: 'blanditiis vel fuga odio qui',
        email: 'Donnell@polly.net',
        body: 'sequi expedita quibusdam enim ipsam\nbeatae ad eum placeat\nperspiciatis quis in nulla porro voluptas quia\nesse et quibusdam',
      },
      {
        id: 203,
        name: 'ab enim adipisci laudantium impedit qui sed',
        email: 'Bonita@karl.biz',
        body: 'eum voluptates id autem sequi qui omnis commodi\nveniam et laudantium aut\net molestias esse asperiores et quaerat\npariatur non officia voluptatibus',
      },
      {
        id: 204,
        name: 'autem voluptates voluptas nihil',
        email: 'Shea@angelina.biz',
        body: 'voluptatibus pariatur illo\nautem quia aut ullam laudantium quod laborum officia\ndicta sit consequatur quis delectus vel\nomnis laboriosam laborum vero ipsa voluptas',
      },
      {
        id: 205,
        name: 'et reiciendis ullam quae',
        email: 'Omari@veronica.us',
        body: 'voluptatem accusamus delectus natus quasi aliquid\nporro ab id ea aut consequatur dignissimos quod et\naspernatur sapiente cum corrupti\npariatur veritatis unde',
      },
    ],
  },
  {
    id: 51,
    title: 'Soluta aliquam aperiam consequatur illo quis voluptas',
    body: 'Sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem',
    user: {
      id: 6,
      name: 'Jaloliddin Olimov',
      username: '@olimov',
      email: 'Karley_Dach@jasper.info',
      phone: '+998975269919',
      website: '/images/jaloladdin.jpg',
    },
    comments: [
      {
        id: 251,
        name: 'veritatis sint eius',
        email: 'Ayden_Hickle@stephany.tv',
        body: 'sit vero at voluptatem corporis adipisci\nerror sit aut nihil rerum doloremque dolorum ipsum\neum ut numquam sapiente ipsam nam blanditiis ut quasi\nfacilis optio rerum qui temporibus esse excepturi eaque',
      },
      {
        id: 252,
        name: 'qui alias beatae iusto omnis placeat recusandae ut',
        email: 'Carissa.Krajcik@jean.name',
        body: 'exercitationem quisquam sed\neius et cum reiciendis deleniti non\nperspiciatis aut voluptatum deserunt\nsint dignissimos est sed architecto sed',
      },
      {
        id: 253,
        name: 'voluptate ipsum corporis quis provident voluptatem eos asperiores',
        email: 'Jayde@geovanny.io',
        body: 'debitis dignissimos ut illum\nrerum voluptatem ut qui labore\noptio quaerat iure\niste consequuntur praesentium vero blanditiis quibusdam aut',
      },
      {
        id: 254,
        name: 'velit inventore et eius saepe',
        email: 'Ardella@khalid.biz',
        body: 'laboriosam voluptas aut quibusdam mollitia sunt non\ndolores illum fugiat ex vero nemo aperiam porro quam\nexpedita est vel voluptatem sit voluptas consequuntur quis eligendi\nomnis id nisi ducimus sapiente odit quam',
      },
      {
        id: 255,
        name: 'impedit et sapiente et tempore repellendus',
        email: 'Delta_Welch@carleton.tv',
        body: 'nihil esse aut\ndebitis nostrum mollitia similique minus aspernatur possimus\nomnis eaque non eveniet\nrerum qui iure laboriosam',
      },
    ],
  },
  {
    id: 61,
    title: '24/7 👨🏼‍💻🌐 Web developer | Frᴏnᴛᴇnd |',
    body: 'Ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit',
    user: {
      id: 7,
      name: 'Sardor',
      username: '@software_deve1oper',
      email: 'Telly.Hoeger@billy.biz',
      phone: '+998900114143',
      website: '/images/sardor.jpg',
    },
    comments: [
      {
        id: 301,
        name: 'id voluptatibus voluptas occaecati quia sunt eveniet et eius',
        email: 'Tiana@jeramie.tv',
        body: 'dolore maxime saepe dolor asperiores cupiditate nisi nesciunt\nvitae tempora ducimus vel eos perferendis\nfuga sequi numquam blanditiis sit sed inventore et\nut possimus soluta voluptas nihil aliquid sed earum',
      },
      {
        id: 302,
        name: 'quia voluptatem sunt voluptate ut ipsa',
        email: 'Lindsey@caitlyn.net',
        body: 'fuga aut est delectus earum optio impedit qui excepturi\niusto consequatur deserunt soluta sunt\net autem neque\ndolor ut saepe dolores assumenda ipsa eligendi',
      },
      {
        id: 303,
        name: 'excepturi itaque laudantium reiciendis dolorem',
        email: 'Gregory.Kutch@shawn.info',
        body: 'sit nesciunt id vitae ut itaque sapiente\nneque in at consequuntur perspiciatis dicta consequatur velit\nfacilis iste ut error sed\nin sequi expedita autem',
      },
      {
        id: 304,
        name: 'voluptatem quidem animi sit est nemo non omnis molestiae',
        email: 'Murphy.Kris@casimer.me',
        body: 'minus ab quis nihil quia suscipit vel\nperspiciatis sunt unde\naut ullam quo laudantium deleniti modi\nrerum illo error occaecati vel officiis facere',
      },
      {
        id: 305,
        name: 'non cum consequatur at nihil aut fugiat delectus quia',
        email: 'Isidro_Kiehn@cristina.org',
        body: 'repellendus quae labore sunt ut praesentium fuga reiciendis quis\ncorporis aut quis dolor facere earum\nexercitationem enim sunt nihil asperiores expedita\neius nesciunt a sit sit',
      },
    ],
  },
  {
    id: 71,
    title: 'Hech qachon kelajakni kutma aksincha kelajakga intil',
    body: 'Occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis',
    user: {
      id: 8,
      name: 'Samandar',
      username: '@Samandar_03_11_03',
      email: 'Sherwood@rosamond.me',
      phone: '586.493.6943 x140',
      website: '/images/samandar.jpg',
    },
    comments: [
      {
        id: 351,
        name: 'quia ex perspiciatis sunt voluptatem quidem',
        email: 'Solon.Goldner@judah.org',
        body: 'quo nisi impedit velit repellendus esse itaque ut saepe\nvoluptatibus occaecati ab eaque dolores\nmaxime alias velit ducimus placeat sit laudantium quia\ncorrupti doloremque ut',
      },
      {
        id: 352,
        name: 'sit ipsam voluptatem velit',
        email: 'Nina@osbaldo.name',
        body: 'dolorem eius voluptatem vitae aliquid unde labore est\nmolestiae labore dolorem beatae voluptatem soluta eum eos dolore\net ea quasi aut doloribus sint\nvel suscipit tempora delectus soluta',
      },
      {
        id: 353,
        name: 'consequatur reprehenderit similique vitae dolor debitis',
        email: 'Madaline@marlin.org',
        body: 'nemo aut laborum expedita nisi sed illum\nab asperiores provident\na sunt recusandae ut rerum itaque est voluptatibus nihil\nesse ipsum et repellendus nobis rerum voluptas et',
      },
      {
        id: 354,
        name: 'eligendi tempora eum deserunt',
        email: 'Mike.Kozey@gladyce.us',
        body: 'delectus est consequatur\nat excepturi asperiores dolor nesciunt ad\nid non aut ad ut\nnon et voluptatem',
      },
      {
        id: 355,
        name: 'reiciendis ad ea',
        email: 'Orval.Treutel@arnold.me',
        body: 'vel cumque labore vitae quisquam magnam sequi ut\nmolestiae dolores vel minus aut\nquas repellat nostrum fugit molestiae veritatis sequi\nvel quidem in molestiae id doloribus sed',
      },
    ],
  },
  {
    id: 81,
    title: 'Tempora rem veritatis voluptas quo dolores vero',
    body: 'Facere qui nesciunt est voluptatum voluptatem nisi\nsequi eligendi necessitatibus ea at rerum itaque\nharum non ratione velit laboriosam quis consequuntur\nex officiis minima doloremque voluptas ut aut',
    user: {
      id: 9,
      name: 'Smailov Nodir',
      username: '@sma1lov_N1337',
      email: 'Chaim_McDermott@dana.io',
      phone: '(775)976-6794 x41206',
      website: '/images/nodir.jpg',
    },
    comments: [
      {
        id: 401,
        name: 'cum voluptate sint voluptas veritatis',
        email: 'Vella.Mayer@colten.net',
        body: 'sit delectus recusandae qui\net cupiditate sed ipsum culpa et fugiat ab\nillo dignissimos quo est repellat dolorum neque\nvoluptates sed sapiente ab aut rerum enim sint voluptatum',
      },
      {
        id: 402,
        name: 'ut eos mollitia eum eius',
        email: 'Caleb_Dach@kathleen.us',
        body: 'et nisi fugit totam\nmaiores voluptatibus quis ipsa sunt debitis assumenda\nullam non quasi numquam ut dolores modi recusandae\nut molestias magni est voluptas quibusdam corporis eius',
      },
      {
        id: 403,
        name: 'architecto voluptatum eos blanditiis aliquam debitis beatae nesciunt dolorum',
        email: 'Patience_Bahringer@dameon.biz',
        body: 'et a et perspiciatis\nautem expedita maiores dignissimos labore minus molestiae enim\net ipsam ea et\nperspiciatis veritatis debitis maxime',
      },
      {
        id: 404,
        name: 'officia qui ut explicabo eos fugit',
        email: 'Destinee.Simonis@jose.tv',
        body: 'modi est et eveniet facilis explicabo\nvoluptatem saepe quo et sint quas quia corporis\npariatur voluptatibus est iste fugiat delectus animi rerum\ndoloribus est enim',
      },
      {
        id: 405,
        name: 'incidunt commodi voluptatem maiores asperiores blanditiis omnis ratione',
        email: 'Keshaun@brown.biz',
        body: 'aut aut sit cupiditate maxime praesentium occaecati cumque\nvero sint sit aliquam porro quo consequuntur ut\nnumquam qui maxime voluptas est consequatur ullam\ntenetur commodi qui consectetur distinctio eligendi atque',
      },
    ],
  },
  {
    id: 91,
    title: '18 y.o. Frontend>/<Developer👨‍💻 (teaching)',
    body: 'Libero voluptate eveniet aperiam sed\nSunt placeat suscipit molestias',
    user: {
      id: 10,
      name: 'Abdulbasit Yuldashev',
      username: '@Yuldashev_A',
      email: 'Rey.Padberg@karina.biz',
      phone: '024-648-3804',
      website: '/images/abdulbasit.jpg',
    },
    comments: [
      {
        id: 451,
        name: 'maiores ut dolores quo sapiente nisi',
        email: 'Duane_Dach@demario.us',
        body: 'dolor veritatis ipsum accusamus quae voluptates sint voluptatum et\nharum saepe dolorem enim\nexpedita placeat qui quidem aut et et est\nminus odit qui possimus qui saepe',
      },
      {
        id: 452,
        name: 'quia excepturi in harum repellat consequuntur est vel qui',
        email: 'General@schuyler.org',
        body: 'ratione sequi sed\nearum nam aut sunt\nquam cum qui\nsimilique consequatur et est',
      },
      {
        id: 453,
        name: 'doloremque ut est eaque',
        email: 'Stephania_Stanton@demond.biz',
        body: 'quidem nisi reprehenderit eligendi fugiat et et\nsapiente adipisci natus nulla similique et est\nesse ea accusantium sunt\ndeleniti molestiae perferendis quam animi similique ut',
      },
      {
        id: 454,
        name: 'magni quos voluptatibus earum et inventore suscipit',
        email: 'Reinhold.Schiller@kelly.info',
        body: 'consequatur accusamus maiores dolorem impedit repellendus voluptas rerum eum\nquam quia error voluptatem et\ndignissimos fugit qui\net facilis necessitatibus dignissimos consequatur iusto nihil possimus',
      },
      {
        id: 455,
        name: 'assumenda qui et aspernatur',
        email: 'Royce@jaiden.co.uk',
        body: 'animi qui nostrum rerum velit\nvoluptates sit in laborum dolorum omnis ut omnis\nea optio quia necessitatibus delectus molestias sapiente perferendis\ndolores vel excepturi expedita',
      },
    ],
  },
];
